sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t DeathGripVT757/multi-nginx -f ./client/Dockerfuke.dev ./client
script:
  - docker run -e CI=true DeathGripVT757/multi-nginx npm test
after_success:
  - docker build -t DeathGripVT757/multi-client ./client
  - docker build -t DeathGripVT757/multi-nginx ./nginx
  - docker build -t DeathGripVT757/multi-server ./server
  - docker build -t DeathGripVT757/multi-worker ./worker
# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
- docker push DeathGRIPVT757/multi-client
- docker push DeathGRIPVT757/multi-nginx
- docker push DeathGRIPVT757/multi-server
- docker push DeathGRIPVT757/multi-worker